import Head from "next/head";
import {useSession} from "next-auth/client";

import Header from "../components/organisms/Header/container";

export default function Home() {
  const [session, loading] = useSession();

  return (
    <>
      <Head>
        <title>Fituu</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header session={session} alternative={false} />  
    </>
  );
}
